export const DELIVERY_FEE = 200;

export const PRODUCT_PRICE_BY_ID = Object.freeze({
  "1-3kg-fireball": 5450,
  "2-door-interlocking-module": 3500,
  "hikvision-colorvu-dome-camera-24-7-color-video-in-kenya": 3500,
  "hikvision-colorvu-bullet-camera-available-in-kenya": 3500,
  "2-2m-2-2-4-4m-double-telescopic-aluminium-ladder": 17300,
  "2-3m-single-telescopic-aluminium-ladder-6-step": 9500,
  "buy-2-6-meters-telescopic-ladder-from-secu-depo-kenya": 17999,
  "2-7m-single-telescopic-aluminium-ladder-7-step": 13500,
  "28fts-4by7-multipurpose-fiberglass-ladders": 31000,
  "2by10-fiberglass-extension-ladder-6m": 48500,
  "2by12-step-fiberglass-extension-ladder-7-4m": 35000,
  "2by14-fiberglass-ladder-8-6m": 56899,
  "2by16-fiberglass-ladder-9-8m": 47000,
  "2m-telescopic-ladder": 12500,
  "2mp-hdcvi-ir-bullet-camera-hac-b1a21": 1750,
  "3-step-steel-ladder": 9000,
  "3-steps-house-hold-aluminium-ladder": 5500,
  "3-step-steel-ladder-2": 9800,
  "3-2m-aluminium-telescopic-ladder-2": 16500,
  "3-8m-1-91-9m-double-telescopic-ladder": 18500,
  "3-8m-aluminium-telescopic-ladder": 17500,
  "3-9m-single-telescopic-aluminium-ladder-10-step": 15900,
  "305-m-cat6-utp-network-cable-solid-copper-0-55-mm-orange": 14500,
  "350kgs-magnetic-lock": 6500,
  "4-by-2-multipurpose-aluminium-ladder-8ft": 10500,
  "4-core-alarm-cable": 1500,
  "4-step-steel-ladder": 10499,
  "4-steps-house-hold-aluminium-ladder": 7300,
  "4-step-steel-ladder-2": 11499,
  "4-1m-telescopic-aluminium-ladder": 18500,
  "2-2m-double-telescopic-ladder": 23300,
  "4-4m-telescopic-aluminium-ladder": 19500,
  "4by10-aluminium-folding-ladder-40ft": 48999,
  "4by3-red-aluminium-multi-purpose-ladder-12ft": 16999,
  "4by3-aluminium-folding-ladder-12ft": 9999,
  "4by4-aluminum-multi-purpose-ladder-16ft": 17500,
  "4by5-aluminium-multi-purpose-ladder-20ft": 16500,
  "4by6-aluminium-folding-ladder-24ft": 22900,
  "4by7-aluminium-folding-ladder-28ft": 32000,
  "4by8-aluminium-folding-ladder-32ft": 38000,
  "4kg-co2-fire-extinguisher": 4800,
  "5-step-aluminium-ladder": 9499,
  "5-step-steel-ladder": 11499,
  "5-step-steel-ladder-2": 12600,
  "5-0m-double-telescopic-aluminium-ladder": 27600,
  "5-0m-telescopic-aluminium-ladder": 21000,
  "5-6m-double-telescopic-aluminium-ladder": 26500,
  "500kg-magnetic-door-lock": 9000,
  "5kg-carbon-dioxide-fire-extinguisher": 7999,
  "5meters-2-52-5m-double-aluminium-telescopic-ladder": 28800,
  "6-core-alarm-cable": 1600,
  "6-kgs-dry-powder-fire-extinguisher": 3999,
  "6-step-steel-ladder": 12499,
  "6-steps-house-hold-aluminium-ladder": 10200,
  "6-step-steel-ladder-2": 13600,
  "7-step-household-aluminium-ladder": 11299,
  "8-core-alarm-cable": 2000,
  "8-steps-house-hold-aluminium-ladder": 12000,
  "9-steps-household-aluminium-ladder": 13999,
  "access-control-exit-buttons-ladders-cctv-electric-fences-accessories": 1500,
  "access-control-power-supply-unit-12v-3a": 2500,
  "access-control-power-supply-unit-12v-5a": 3300,
  "ace-100-hammer-energizer": 24999,
  "ace-200-hammer-energizer": 27999,
  "addressable-glass-weatherproof-call-point-w5a-rpo5sf-k013-morley-ias": 10399,
  "alarm-strobe-light-12v": 1200,
  "aluminium-braided-wire-1-6mm-1000m-4": 9500,
  "aluminium-ht-wire": 8500,
  "asenware-convectional-fire-alarm-smoke-detector": 1500,
  "asenware-fire-alarm-bell": 4399,
  "asenware-fire-alarm-cable-1-5mm": 10800,
  "asenware-fire-alarm-heat-detector": 1450,
  "asenware-fire-bell-sounder": 3500,
  "asenware-lpg-gas-leak-detector-with-shut-off-valve": 7400,
  "asenware-standalone-smoke-detector": 1500,
  "audio-door-phone": 5000,
  "automatic-door-opener-side-mounted-300kg-heavy-duty-swing-gate-motor": 35000,
  "automatic-voltage-switcher-avs30": 7200,
  "avs13-surge-protector": 5700,
  "baofeng-bf-888s-2way-radio-pair": 3299,
  "baofeng-uv-82-walkie-talkie": 4000,
  "biometric-attendance-systems": 45000,
  "aluminium-blind-rivets-pop-rivets-secu-depo": 850,
  "c-tec-addressable-heat-detector": 5700,
  "c-tec-xfp-2-loop-32-zone-addressable-fire-alarm-panel": 144899,
  "car-under-vehicle-search-security-mirror": 6400,
  "card-reader-ds-k1102mk": 6500,
  "cat6-u-utp-network-cable-solid-copper-0-5mm": 12500,
  "cctv-power-supply-18-channels-12v-20a": 3500,
  "cctv-power-supply-box": 2500,
  "cctv-power-supply-unit-12v-10-amps": 1500,
  "cctv-power-supply-unit-12v-30a": 2500,
  "centurion-d10-industrial-sliding-gate-motor": 130000,
  "ccenturion-d5-evo-sliding-gate-motor": 58000,
  "centurion-d5-smart-gate-motor": 59000,
  "centurion-g-speak-gsm-gate-module": 24900,
  "centurion-ga42-gate-wheel-kit-800kg": 8990,
  "centurion-i5-infrared-gate-safety-beam": 6700,
  "centurion-nova-1ch-remote-button": 1800,
  "centurion-photon-beam-sensors": 10500,
  "centurion-remote-gate-buttons": 3500,
  "centurion-sliding-gate-motor": 80000,
  "centurion-vantage-smart-swing-gate-operator": 105000,
  "centurion-vantage-swing-gate-motor": 104000,
  "chain-strainer-wire-tensioner": 6999,
  "co2-wheeled-fire-extinguisher-10kg": 19499,
  "comet-pir-motion-sensor-ladders-cctv-electric-fences-accessories": 1500,
  "conventional-fire-strobe-sounder": 2100,
  "conventional-manual-call-point-with-indicator": 1500,
  "convex-mirror-80cm-safety-security-surveillance-black": 14999,
  "cooper-menvier-cmio353-addressable-230vac-relay-unit": 21899,
  "cooper-menvier-conventional-2-zone-fire-panel": 35000,
  "cooper-menvier-conventional-4-zone-fire-panel": 38950,
  "cooper-menvier-fx2208cfcpd-conventional-8-zone-control-panel": 79899,
  "cooper-menvier-mab50r-addressable-reflective-beam-detector-50m-range": 105999,
  "cooper-menvier-mbd50r": 85000,
  "cps-6000-single-zone-hammer-energizer": 36999,
  "cps-6002-dual-zone-energizer-hammer": 65000,
  "cps-6004-4-zone-hammer-energizer": 106999,
  "crimping-tool": 750,
  "d10-smart-centurion-gate-motor": 119000,
  "d20-smart-centurion-gate-motor": 148000,
  "d6-smart-centurion-gate-motor": 65000,
  "digital-persona-4500-fingerprint-reader": 12499,
  "door-infrared-no-touch-exit-button": 2200,
  "double-door-magnetic-lock": 10000,
  "double-sided-aluminum-step-ladders": 5100,
  "dual-frequency-rfid-cards-125khz-em4100-and-13-56mhz-mifare-classic-1k": 300,
  "duraline-delivery-hose-30-metres": 28900,
  "quality-electric-fence-earth-rods-available-in-kenya-electric-fence-earth-rods": 400,
  "electric-automatic-door-closer": 29000,
  "electric-drop-bolt-lock": 3999,
  "electric-fence-installation-kenya": 85000,
  "electric-fence-light-indicator": 1999,
  "electric-fence-meter-voltage-meter": 5000,
  "electric-fence-polywire": 3500,
  "electric-fence-warning-signs": 300,
  "electric-strike-lock": 3999,
  "elock-vibration-sensor": 400,
  "emergency-break-glass": 1000,
  "emergency-break-glass-access-control-emergency-door-release-emergency-exit": 1200,
  "exodus-oh-heat-detector": 4200,
  "exodus-oh-smoke-detector": 4300,
  "ezviz-c6n-wifi-360-nanny-camera": 6299,
  "ezviz-hd-resolution-indoor-wi-fi-camera": 6500,
  "fire-alarm-cable-0-8mm": 4500,
  "fire-resistant-cable-fire-alarm-cable": 6500,
  "fr1200-fingerprint-reader": 8500,
  "buy-gallagher-electric-fence-tester-in-kenya": 21499,
  "galvanized-high-tensile-wire-1-6mm": 7500,
  "galvanized-high-tensile-wire-2-5mm-50kg": 10400,
  "garrett-hand-held-metal-detector": 2499,
  "garrett-super-wand-hand-held-metal-detector": 5500,
  "garrett-walk-through-metal-detector": 295000,
  "giganet-cat-6-utp-pure-copper-ethernet-cable-305m": 25000,
  "giganet-cat6a-u-utp-outdoor-ldpe-cable-305m": 26900,
  "green-razor-wire": 2200,
  "green-razor-wire-450mm-4": 1900,
  "gsm-desk-phone-phone-ets-6588": 3850,
  "hammer-energizer-ez-630-2": 14399,
  "hammer-energizer-ez-640": 18000,
  "hammer-energizer-ez-680": 30000,
  "hammer-energizer-led-keypad": 12000,
  "hammer-remote-key-switch-2": 5500,
  "hammer-energizer-surge-stop-secu-depo-kenya": 4100,
  "hdmi-switch-5-port": 5000,
  "heavy-duty-4by3-aluminium-folding-ladder-12ft": 12500,
  "heavy-duty-4by4-aluminum-multi-purpose-ladder-16ft": 12900,
  "hid-rfid-cards-for-access-control": 290,
  "hikvision-16-channel-dvr": 13000,
  "hikvision-2mp-hd-bullet-camera": 2000,
  "hikvision-2mp-network-bullet-camera": 4500,
  "hikvision-2mp-network-dome-camera": 4500,
  "hikvision-32-channel-dvr-1080p": 27000,
  "hikvision-4-channel-dvr": 5500,
  "hikvision-4-channel-nvr": 12000,
  "hikvision-bullet-camera-2mp": 1800,
  "hikvision-dome-camera-2mp": 1800,
  "hikvision-ds-2de4225iw-de-t5-ptz-ip-speed-dome-camera-2mp": 38000,
  "hikvision-utp-cat6-cable": 14899,
  "hikvision16-channel-dvr": 18000,
  "honeywell-farenhyt-idp-heat-w-series": 7500,
  "honeywell-farenhyt-idp-pull-da-addressable-dual-action-manual-pull-station": 10500,
  "honeywell-idp-photo-w-intelligent-photoelectric-smoke-detector-white": 7500,
  "hydraulic-door-closer": 6000,
  "inbio-4-door-controller-suppliers-in-kenya-inbio-4-door-controller": 45000,
  "infrared-beam-detector": 4000,
  "insupipe-for-electric-fence-on-wooden-posts": 400,
  "iwise-dt-am-grade-3": 4500,
  "jva-electric-fence-fault-finder": 14900,
  "bm1-jva-fence-monitor-bm1-ladders-cctv-electric-fences-accessories": 16500,
  "jva-z13-single-zone-security-energizer-2-8joule": 24000,
  "jva-z14-energizer-5-joule-with-lcd-display": 28000,
  "jva-z28-2-zone-security-energizer-8-joule-with-lcd-display": 53000,
  "keyguard-emergency-key-box": 3500,
  "kx-ts500-panasonic-landline-phone": 2499,
  "lcd-keypad-hammer": 13000,
  "lightsys-8-zone-expander": 8000,
  "lunar-pir-ceiling-detector": 4000,
  "magnetic-door-contacts": 450,
  "magnetic-door-lock-180kg": 2300,
  "cooper-menvier-cap320-intelligent-addressable-optical-smoke-sensor": 4500,
  "mifare-cards-13-56mhz": 128,
  "mifare-desfire-ev2-8k-nfc-card": 290,
  "multipurpose-fiberglass-ladders": 23000,
  "multipurpose-fiberglass-ladders-4by3-12ft": 23000,
  "multipurpose-fiberglass-ladders-4by4-16fts": 27000,
  "multipurpose-fiberglass-ladders-4by5-20fts": 25000,
  "multipurpose-fiberglass-ladders-4by6-24fts": 30000,
  "nemtek-druid-114-lcd-energizer": 59000,
  "nemtek-druid-13-lcd-energizer-2": 22500,
  "nemtek-druid-13-lcd-energizer": 20999,
  "nemtek-druid-15-lcd-energizer": 24499,
  "nemtek-druid-18-lcd-energizer": 39999,
  "nemtek-druid-18lcd-energizer": 38000,
  "nemtek-druid-2-zone-keypad": 9999,
  "nemtek-druid-25-lcd-energizer": 46999,
  "nemtek-druid-28-lcd-electric-fence-energizer": 48000,
  "nemtek-druid-4-zone-keypad": 15799,
  "nemtek-druid-single-zone-keypad": 6999,
  "nemtek-lightning-diverter-kit-dealers-in-kenya-nemtek-lightning-diverter-kit": 3999,
  "nemtek-sliding-gate-contacts": 6500,
  "nemtek-wizord-2-energizer": 19000,
  "nemtek-wizord-4-energizer": 25000,
  "notifier-b501-plug-in-detector-base": 1500,
  "override-key-switch": 1500,
  "panduit-tx6a-category-6a-u-utp-copper-cable": 28000,
  "panic-buttons": 400,
  "panic-button-remote-ptx1-sherlotronics": 2500,
  "photoelectric-beam-sensor-kenya": 8400,
  "pop-rivet-gun": 3800,
  "pop-rivet-gun-2": 3800,
  "porcelain-bullnose-strainer-insulator": 80,
  "porcelain-electric-fence-insulators-4": 80,
  "prosys-control-panel-features-risco-prosys-plus-panel": 40000,
  "prosys-lcd-keypads": 12000,
  "prysmian-1-5mm%c2%b2-fp200-gold-fire-fire-resistant-alarm-cable": 41000,
  "push-to-exit-button": 400,
  "razor-wire-450mm": 1420,
  "razor-wire-730mm": 3399,
  "reflective-fire-exit-sign": 6500,
  "relay-board": 600,
  "rfid-cards-for-access-control": 49,
  "rg59-coaxial-cable-with-power-100-meters": 3500,
  "rg59-coaxial-cable-with-power-200-meters": 5500,
  "rg59-copper-coaxial-cable-305-meters": 8000,
  "lightsys-alarm-panel": 24500,
  "risco-lightsys-gsm-module": 22000,
  "risco-lightsys-lcd-keypad": 8500,
  "rj45-hdmi-extender": 1500,
  "roller-shutter-magnetic-door-sensor": 2000,
  "s922-portable-time-attendance-device": 79000,
  "safety-parking-convex-mirror": 17500,
  "secolink-graphic-lcd-keypads-km24a-and-km24g": 7500,
  "sestic-glue": 150,
  "sherlo-tronics-ptx1-panic-button": 2000,
  "sherlotronic-remote-button": 2000,
  "sherlotronics-4-channel-receiver-500m-range-rx4-500": 8500,
  "sherlotronics-power-supply-unit-3-2a-2": 4500,
  "sherlotronics-remote-button-tx1": 2000,
  "sherlotronics-remote-kit": 6800,
  "sherlotronics-receiver-rx4-500-available-in-kenya": 9000,
  "siemon-cat-6-category-6-unshielded-twisted-pair-utp-cable": 21900,
  "siren-box": 1200,
  "siren-horn-15-watts": 1000,
  "siren-horn-30-watt": 3500,
  "siren-kit-alarm-kit": 2500,
  "sliding-gate-guide-rollers": 4500,
  "sliding-gate-rollers-wheels": 7500,
  "sliding-gate-steel-gear-rack-rail": 4400,
  "sliding-gate-wheels-rollers": 7400,
  "solar-powered-4g-intelligent-ptz-camera": 14600,
  "stafix-46000w-mains-energizer": 205000,
  "stafix-x18i-energizer": 178000,
  "stafix-x3-energizer": 49500,
  "stafix-x6-energizer": 79500,
  "stainless-steel-exit-button": 1200,
  "standalone-access-control-keypad-s601em": 7500,
  "strainer-insulators-for-electric-fence": 8,
  "suprema-bew2-odp-outdoor-ip-fingerprint-reader": 79000,
  "suprema-bio-mini-slim-2-fap20-fingerprint-scanner": 22500,
  "suprema-bioentry-p2": 66000,
  "suprema-bioentry-plus": 46000,
  "suprema-biostation-3-facial-recognition-bs3-db": 175000,
  "suprema-biostation-l2-fingerprint-biometric-device": 95000,
  "suprema-xp2-mdpb-xpass-2-outdoor-compact-rfid-reader": 44000,
  "suprema-xpass-d2": 45000,
  "surge-protector-for-centurion-gate-motors": 5200,
  "t5577-125khz-writable-thin-proximity-cards": 380,
  "tk4100-rfid-cards": 50,
  "triband-gsm-signal-booster-2g-3g-4g": 12400,
  "u-bracket-for-magnetic-lock": 1799,
  "uv-treated-electric-fence-w-insulators": 35,
  "w-post-electric-fence": 300,
  "wd-1tb-surveillance-hard-disk": 5000,
  "wd-500gb-internal-hard-disk": 3000,
  "wd-purple-2tb-surveillance-hard-disk-drive": 5450,
  "wd-purple-pro-surveillance-hard-drive-10tb-512mb-wd101purp": 26999,
  "weather-proof-conventional-fire-strobe-sounder": 3399,
  "wifi-bulb-camera-1080p-suppliers-in-kenya": 3200,
  "yuasa-12v-17ah-sealed-lead-acid-battery": 4800,
  "zkteco-f18-biometric-reader": 15899,
  "zkteco-f21-biometric-reader-advanced-access-control-kenya": 24000,
  "zkteco-f22-fingerprint-reader": 16000,
  "zkteco-inbio-4-door-access-controller-3": 54000,
  "zkteco-k40-time-attendance-terminal": 11999,
  "zkteco-mb360": 18999,
  "zkteco-mb560-vl": 28000,
  "zkteco-s922-portable-bio-metric-system": 68000,
  "speedface-v5l-suppliers-kenya": 55000,
  "zkteco-speedface-v4l": 28000,
  "zkteco-tf1700-biometric-reader": 27000,
  "zkteco-zk4500-fingerprint-scanner-2": 9000,
});

export const PRODUCT_NAME_BY_ID = Object.freeze({
  "1-3kg-fireball": "1.3kg fireball",
  "2-door-interlocking-module": "2 Door Interlocking Module",
  "hikvision-colorvu-dome-camera-24-7-color-video-in-kenya": "2 MP ColorVu Dome Fixed Camera",
  "hikvision-colorvu-bullet-camera-available-in-kenya": "2 MP ColorVu Fixed Bullet Camera",
  "2-2m-2-2-4-4m-double-telescopic-aluminium-ladder": "2.2m +2.2. (4.4M) Double Telescopic Aluminium Ladder",
  "2-3m-single-telescopic-aluminium-ladder-6-step": "2.3M Single Telescopic Aluminium Ladder (6 step)",
  "buy-2-6-meters-telescopic-ladder-from-secu-depo-kenya": "2.6 Meters Telescopic Ladder",
  "2-7m-single-telescopic-aluminium-ladder-7-step": "2.7M Single Telescopic Aluminium Ladder (7 step)",
  "28fts-4by7-multipurpose-fiberglass-ladders": "28fts 4by7 Multipurpose Fiberglass Ladders",
  "2by10-fiberglass-extension-ladder-6m": "2by10 Fiberglass Extension Ladder (6M)",
  "2by12-step-fiberglass-extension-ladder-7-4m": "2by12 Step Fiberglass Extension Ladder (7.4M)",
  "2by14-fiberglass-ladder-8-6m": "2by14 Fiberglass Ladder (8.6M)",
  "2by16-fiberglass-ladder-9-8m": "2by16 Fiberglass Ladder (9.8M)",
  "2m-telescopic-ladder": "2M Telescopic ladder",
  "2mp-hdcvi-ir-bullet-camera-hac-b1a21": "2MP HDCVI IR Bullet Camera HAC-B1A21",
  "3-step-steel-ladder": "3 Step Steel Ladder",
  "3-steps-house-hold-aluminium-ladder": "3 Steps House Hold Aluminium Ladder",
  "3-step-steel-ladder-2": "3-Step Steel Ladder",
  "3-2m-aluminium-telescopic-ladder-2": "3.2m aluminium telescopic ladder",
  "3-8m-1-91-9m-double-telescopic-ladder": "3.8M 1.9+1.9m Double Telescopic Ladder",
  "3-8m-aluminium-telescopic-ladder": "3.8M Aluminium Telescopic Ladder",
  "3-9m-single-telescopic-aluminium-ladder-10-step": "3.9M Single Telescopic Aluminium Ladder (10 step)",
  "305-m-cat6-utp-network-cable-solid-copper-0-55-mm-orange": "305 m CAT6 UTP Network Cable (Solid Copper, 0.55 mm, Orange)",
  "350kgs-magnetic-lock": "350Kgs Magnetic Lock",
  "4-by-2-multipurpose-aluminium-ladder-8ft": "4 by 2 Multipurpose Aluminium Ladder 8ft",
  "4-core-alarm-cable": "4 Core Alarm Cable",
  "4-step-steel-ladder": "4 Step Steel Ladder",
  "4-steps-house-hold-aluminium-ladder": "4 Steps House Hold Aluminium Ladder",
  "4-step-steel-ladder-2": "4-Step Steel Ladder",
  "4-1m-telescopic-aluminium-ladder": "4.1M Telescopic Aluminium Ladder",
  "2-2m-double-telescopic-ladder": "4.4 Meters 2.2+2.2M Double Telescopic Ladder",
  "4-4m-telescopic-aluminium-ladder": "4.4M Telescopic Aluminium Ladder",
  "4by10-aluminium-folding-ladder-40ft": "4by10 aluminium folding ladder 40ft",
  "4by3-red-aluminium-multi-purpose-ladder-12ft": "4by3 (Red) aluminium multi-purpose ladder 12ft",
  "4by3-aluminium-folding-ladder-12ft": "4by3 Aluminium Folding Ladder 12ft",
  "4by4-aluminum-multi-purpose-ladder-16ft": "4by4 Aluminum Multi Purpose Ladder 16ft",
  "4by5-aluminium-multi-purpose-ladder-20ft": "4by5 aluminium multi-purpose ladder 20ft",
  "4by6-aluminium-folding-ladder-24ft": "4by6 Aluminium Folding Ladder 24ft",
  "4by7-aluminium-folding-ladder-28ft": "4by7 Aluminium Folding Ladder 28ft",
  "4by8-aluminium-folding-ladder-32ft": "4by8 Aluminium Folding Ladder 32ft",
  "4kg-co2-fire-extinguisher": "4kg CO2 Fire Extinguisher",
  "5-step-aluminium-ladder": "5 Step Aluminium Ladder",
  "5-step-steel-ladder": "5 Step Steel Ladder",
  "5-step-steel-ladder-2": "5-Step Steel Ladder",
  "5-0m-double-telescopic-aluminium-ladder": "5.0M Double Telescopic Aluminium Ladder",
  "5-0m-telescopic-aluminium-ladder": "5.0M Telescopic Aluminium Ladder",
  "5-6m-double-telescopic-aluminium-ladder": "5.6M Double telescopic aluminium ladder",
  "500kg-magnetic-door-lock": "500Kg Magnetic Door Lock",
  "5kg-carbon-dioxide-fire-extinguisher": "5Kg Carbon Dioxide Fire Extinguisher",
  "5meters-2-52-5m-double-aluminium-telescopic-ladder": "5meters 2.5+2.5M Double Aluminium Telescopic Ladder",
  "6-core-alarm-cable": "6 Core Alarm Cable",
  "6-kgs-dry-powder-fire-extinguisher": "6 Kgs Dry Powder Fire Extinguisher",
  "6-step-steel-ladder": "6 Step Steel Ladder",
  "6-steps-house-hold-aluminium-ladder": "6 Steps House Hold Aluminium Ladder",
  "6-step-steel-ladder-2": "6-Step Steel Ladder",
  "7-step-household-aluminium-ladder": "7 step household aluminium ladder",
  "8-core-alarm-cable": "8 Core Alarm Cable",
  "8-steps-house-hold-aluminium-ladder": "8 Steps House Hold Aluminium Ladder",
  "9-steps-household-aluminium-ladder": "9 Steps household aluminium ladder",
  "access-control-exit-buttons-ladders-cctv-electric-fences-accessories": "Access Control Exit Buttons",
  "access-control-power-supply-unit-12v-3a": "Access Control Power Supply Unit 12V 3A",
  "access-control-power-supply-unit-12v-5a": "Access Control Power Supply Unit 12V 5A",
  "ace-100-hammer-energizer": "Ace 100 Hammer Energizer",
  "ace-200-hammer-energizer": "Ace 200 Hammer Energizer",
  "addressable-glass-weatherproof-call-point-w5a-rpo5sf-k013-morley-ias": "Addressable Glass Weatherproof Call Point W5A-RPO5SF-K013 Morley IAS",
  "alarm-strobe-light-12v": "Alarm strobe light 12v",
  "aluminium-braided-wire-1-6mm-1000m-4": "Aluminium Braided Wire 1.6mm-1000m",
  "aluminium-ht-wire": "Aluminium Ht Wire",
  "asenware-convectional-fire-alarm-smoke-detector": "Asenware Convectional Fire Alarm Smoke Detector",
  "asenware-fire-alarm-bell": "Asenware Fire Alarm Bell",
  "asenware-fire-alarm-cable-1-5mm": "Asenware Fire Alarm cable 1.5mm",
  "asenware-fire-alarm-heat-detector": "Asenware Fire Alarm Heat Detector",
  "asenware-fire-bell-sounder": "Asenware Fire Bell Sound Alarm System",
  "asenware-lpg-gas-leak-detector-with-shut-off-valve": "Asenware LPG Gas Leak Detector With shut off Valve",
  "asenware-standalone-smoke-detector": "Asenware Standalone Smoke Detector",
  "audio-door-phone": "Audio Door Phone",
  "automatic-door-opener-side-mounted-300kg-heavy-duty-swing-gate-motor": "Automatic Door Opener Side-mounted 300kg Heavy Duty Swing Gate Motor",
  "automatic-voltage-switcher-avs30": "Automatic voltage switcher AVS30",
  "avs13-surge-protector": "AVS13 surge protector",
  "baofeng-bf-888s-2way-radio-pair": "Baofeng BF-888S 2Way radio Pair",
  "baofeng-uv-82-walkie-talkie": "Baofeng UV-82 walkie talkie",
  "biometric-attendance-systems": "Biometric Attendance Systems",
  "aluminium-blind-rivets-pop-rivets-secu-depo": "Blind Rivets",
  "c-tec-addressable-heat-detector": "C-Tec Addressable Heat Detector",
  "c-tec-xfp-2-loop-32-zone-addressable-fire-alarm-panel": "C-TEC XFP 2 Loop 32 Zone Addressable Fire Alarm Panel",
  "car-under-vehicle-search-security-mirror": "car under vehicle search security mirror",
  "card-reader-ds-k1102mk": "Card Reader DS-K1102MK",
  "cat6-u-utp-network-cable-solid-copper-0-5mm": "CAT6 U/UTP Network Cable (Solid Copper, 0.5mm)",
  "cctv-power-supply-18-channels-12v-20a": "CCTV Power Supply 18 Channels 12v- 20A",
  "cctv-power-supply-box": "CCTV Power Supply Box",
  "cctv-power-supply-unit-12v-10-amps": "CCTV Power Supply Unit 12V 10 Amps",
  "cctv-power-supply-unit-12v-30a": "CCTV Power Supply Unit 12V 30A",
  "centurion-d10-industrial-sliding-gate-motor": "Centurion D10 Industrial Sliding Gate Motor",
  "ccenturion-d5-evo-sliding-gate-motor": "Centurion D5 Evo Sliding Gate Motor",
  "centurion-d5-smart-gate-motor": "Centurion D5 smart gate motor",
  "centurion-g-speak-gsm-gate-module": "Centurion G Speak GSM Gate Module",
  "centurion-ga42-gate-wheel-kit-800kg": "Centurion GA42 Gate Wheel Kit 800kg",
  "centurion-i5-infrared-gate-safety-beam": "Centurion i5 Infrared Gate Safety Beam",
  "centurion-nova-1ch-remote-button": "Centurion Nova 1ch Remote Button",
  "centurion-photon-beam-sensors": "Centurion Photon Beam Sensors",
  "centurion-remote-gate-buttons": "Centurion Remote Gate Buttons",
  "centurion-sliding-gate-motor": "Centurion Sliding Gate Motor",
  "centurion-vantage-smart-swing-gate-operator": "Centurion Vantage Smart Swing Gate operator",
  "centurion-vantage-swing-gate-motor": "Centurion Vantage Swing Gate Motor",
  "chain-strainer-wire-tensioner": "Chain Strainer Wire Tensioner",
  "co2-wheeled-fire-extinguisher-10kg": "CO2 Wheeled Fire Extinguisher 10kg",
  "comet-pir-motion-sensor-ladders-cctv-electric-fences-accessories": "CoMET PIR Motion Sensor",
  "conventional-fire-strobe-sounder": "Conventional Fire Strobe Sounder",
  "conventional-manual-call-point-with-indicator": "Conventional Manual Call Point With Indicator",
  "convex-mirror-80cm-safety-security-surveillance-black": "Convex Mirror 80cm safety security surveillance (Black)",
  "cooper-menvier-cmio353-addressable-230vac-relay-unit": "Cooper Menvier CMIO353 Addressable 230Vac Relay Unit",
  "cooper-menvier-conventional-2-zone-fire-panel": "Cooper Menvier Conventional 2 zone Fire Panel",
  "cooper-menvier-conventional-4-zone-fire-panel": "Cooper Menvier Conventional 4 zone Fire Panel",
  "cooper-menvier-fx2208cfcpd-conventional-8-zone-control-panel": "Cooper Menvier FX2208CFCPD Conventional 8 Zone Control Panel",
  "cooper-menvier-mab50r-addressable-reflective-beam-detector-50m-range": "Cooper Menvier MAB50R Addressable Reflective Beam Detector (50m Range)",
  "cooper-menvier-mbd50r": "Cooper Menvier MBD50R",
  "cps-6000-single-zone-hammer-energizer": "CPS 6000 Single Zone Hammer Energizer",
  "cps-6002-dual-zone-energizer-hammer": "CPS 6002 Dual Zone Energizer Hammer",
  "cps-6004-4-zone-hammer-energizer": "CPS 6004 4 Zone Hammer Energizer",
  "crimping-tool": "crimping tool",
  "d10-smart-centurion-gate-motor": "D10 Smart Centurion Gate Motor",
  "d20-smart-centurion-gate-motor": "D20 Smart Centurion Gate Motor",
  "d6-smart-centurion-gate-motor": "D6 Smart Centurion Gate Motor",
  "digital-persona-4500-fingerprint-reader": "Digital Persona 4500 Fingerprint Reader",
  "door-infrared-no-touch-exit-button": "Door Infrared No Touch Exit Button",
  "double-door-magnetic-lock": "Double Door Magnetic Lock",
  "double-sided-aluminum-step-ladders": "Double Sided Aluminum Step Ladders",
  "dual-frequency-rfid-cards-125khz-em4100-and-13-56mhz-mifare-classic-1k": "Dual Frequency RFID Cards 125khz EM4100 and 13.56Mhz MIFARE Classic 1K",
  "duraline-delivery-hose-30-metres": "Duraline Delivery Hose 30 Metres",
  "quality-electric-fence-earth-rods-available-in-kenya-electric-fence-earth-rods": "Earth Rods",
  "electric-automatic-door-closer": "Electric automatic door closer",
  "electric-drop-bolt-lock": "Electric Drop Bolt Lock",
  "electric-fence-installation-kenya": "Electric Fence Installation Kenya",
  "electric-fence-light-indicator": "Electric Fence Light Indicator",
  "electric-fence-meter-voltage-meter": "Electric Fence Meter | Voltage Meter",
  "electric-fence-polywire": "Electric Fence Polywire",
  "electric-fence-warning-signs": "Electric Fence Warning Signs",
  "electric-strike-lock": "Electric Strike Lock",
  "elock-vibration-sensor": "Elock Vibration Sensor",
  "emergency-break-glass": "Emergency Break Glass",
  "emergency-break-glass-access-control-emergency-door-release-emergency-exit": "Emergency Break Glass Access Control Door Release Emergency Exit",
  "exodus-oh-heat-detector": "Exodus OH Heat Detector",
  "exodus-oh-smoke-detector": "Exodus OH Smoke Detector",
  "ezviz-c6n-wifi-360-nanny-camera": "EZVIZ C6N Wifi 360 Nanny Camera",
  "ezviz-hd-resolution-indoor-wi-fi-camera": "Ezviz hd Resolution Indoor Wi-Fi Camera",
  "fire-alarm-cable-0-8mm": "Fire Alarm Cable 0.8mm",
  "fire-resistant-cable-fire-alarm-cable": "Fire Resistant Cable | Fire Alarm Cable",
  "fr1200-fingerprint-reader": "FR1200 Fingerprint Reader",
  "buy-gallagher-electric-fence-tester-in-kenya": "Gallagher Fence Digital Voltmeter",
  "galvanized-high-tensile-wire-1-6mm": "Galvanized High Tensile Wire 1.6mm",
  "galvanized-high-tensile-wire-2-5mm-50kg": "Galvanized High Tensile Wire 2.5MM 50KG",
  "garrett-hand-held-metal-detector": "Garrett Hand Held Metal Detector",
  "garrett-super-wand-hand-held-metal-detector": "Garrett Super Wand Hand Held Metal Detector",
  "garrett-walk-through-metal-detector": "Garrett walk through metal detector",
  "giganet-cat-6-utp-pure-copper-ethernet-cable-305m": "Giganet Cat 6 UTP Pure Copper Ethernet Cable 305M",
  "giganet-cat6a-u-utp-outdoor-ldpe-cable-305m": "Giganet Cat6A U/UTP Outdoor LDPE Cable 305m",
  "green-razor-wire": "Green Razor Wire",
  "green-razor-wire-450mm-4": "Green razor wire 450mm",
  "gsm-desk-phone-phone-ets-6588": "GSM Desk Phone phone ETS-6588",
  "hammer-energizer-ez-630-2": "Hammer Energizer Ez 630",
  "hammer-energizer-ez-640": "Hammer Energizer EZ 640",
  "hammer-energizer-ez-680": "Hammer Energizer Ez 680",
  "hammer-energizer-led-keypad": "Hammer energizer led keypad",
  "hammer-remote-key-switch-2": "Hammer Remote Key Switch",
  "hammer-energizer-surge-stop-secu-depo-kenya": "Hammer Surge Stop",
  "hdmi-switch-5-port": "Hdmi Switch 5 Port",
  "heavy-duty-4by3-aluminium-folding-ladder-12ft": "Heavy Duty 4by3 Aluminium Folding Ladder 12ft",
  "heavy-duty-4by4-aluminum-multi-purpose-ladder-16ft": "Heavy Duty 4by4 Aluminum Multi Purpose Ladder 16ft",
  "hid-rfid-cards-for-access-control": "HID RFID Cards for Access Control",
  "hikvision-16-channel-dvr": "Hikvision 16 Channel DVR",
  "hikvision-2mp-hd-bullet-camera": "Hikvision 2MP HD Bullet Camera",
  "hikvision-2mp-network-bullet-camera": "Hikvision 2MP Network Bullet Camera",
  "hikvision-2mp-network-dome-camera": "Hikvision 2MP Network Dome Camera",
  "hikvision-32-channel-dvr-1080p": "Hikvision 32 Channel DVR",
  "hikvision-4-channel-dvr": "Hikvision 4 Channel DVR",
  "hikvision-4-channel-nvr": "Hikvision 4 Channel NVR",
  "hikvision-bullet-camera-2mp": "Hikvision Bullet Camera 2MP",
  "hikvision-dome-camera-2mp": "Hikvision Dome Camera 2MP",
  "hikvision-ds-2de4225iw-de-t5-ptz-ip-speed-dome-camera-2mp": "Hikvision DS-2DE4225IW-DE (T5) PTZ IP Speed Dome Camera 2MP",
  "hikvision-utp-cat6-cable": "Hikvision UTP Cat6 Cable",
  "hikvision16-channel-dvr": "Hikvision16 Channel DVR",
  "honeywell-farenhyt-idp-heat-w-series": "Honeywell Farenhyt IDP-HEAT-W Series",
  "honeywell-farenhyt-idp-pull-da-addressable-dual-action-manual-pull-station": "Honeywell Farenhyt IDP-Pull-DA Addressable Dual-Action Manual Pull Station",
  "honeywell-idp-photo-w-intelligent-photoelectric-smoke-detector-white": "Honeywell IDP-PHOTO-W Intelligent Photoelectric Smoke Detector, White",
  "hydraulic-door-closer": "Hydraulic Door Closer",
  "inbio-4-door-controller-suppliers-in-kenya-inbio-4-door-controller": "Inbio 460 4 Door Controller",
  "infrared-beam-detector": "Infrared Beam Detector",
  "insupipe-for-electric-fence-on-wooden-posts": "Insupipe For Electric Fence On Wooden Posts",
  "iwise-dt-am-grade-3": "iWISE DT AM Grade 3",
  "jva-electric-fence-fault-finder": "JVA Electric Fence Fault Finder",
  "bm1-jva-fence-monitor-bm1-ladders-cctv-electric-fences-accessories": "JVA Fence Monitor BM1",
  "jva-z13-single-zone-security-energizer-2-8joule": "JVA Z13 Single Zone Security Energizer 2.8Joule",
  "jva-z14-energizer-5-joule-with-lcd-display": "JVA Z14 Energizer 5 Joule With LCD Display",
  "jva-z28-2-zone-security-energizer-8-joule-with-lcd-display": "JVA Z28 2 Zone Security Energizer 8 Joule with LCD Display",
  "keyguard-emergency-key-box": "Keyguard Emergency Key Box",
  "kx-ts500-panasonic-landline-phone": "KX-TS500 Panasonic Landline Phone",
  "lcd-keypad-hammer": "LCD Keypad Hammer",
  "lightsys-8-zone-expander": "Lightsys 8 Zone Expander",
  "lunar-pir-ceiling-detector": "Lunar PIR Ceiling Detector",
  "magnetic-door-contacts": "Magnetic Door Contacts",
  "magnetic-door-lock-180kg": "magnetic door lock 180kg",
  "cooper-menvier-cap320-intelligent-addressable-optical-smoke-sensor": "Menvier CAP320 Intelligent Addressable Optical Smoke Sensor",
  "mifare-cards-13-56mhz": "Mifare Cards 13.56Mhz",
  "mifare-desfire-ev2-8k-nfc-card": "Mifare DESFire EV2 8k NFC card",
  "multipurpose-fiberglass-ladders": "Multipurpose Fiberglass Ladders",
  "multipurpose-fiberglass-ladders-4by3-12ft": "Multipurpose Fiberglass Ladders 4by3 12ft",
  "multipurpose-fiberglass-ladders-4by4-16fts": "Multipurpose Fiberglass Ladders 4by4 16fts",
  "multipurpose-fiberglass-ladders-4by5-20fts": "Multipurpose Fiberglass Ladders 4by5 20fts",
  "multipurpose-fiberglass-ladders-4by6-24fts": "Multipurpose Fiberglass Ladders 4by6 24fts",
  "nemtek-druid-114-lcd-energizer": "Nemtek Druid 114 LCD Energizer",
  "nemtek-druid-13-lcd-energizer-2": "Nemtek Druid 13 LCD Energizer",
  "nemtek-druid-13-lcd-energizer": "Nemtek Druid 13 LCD Energizer",
  "nemtek-druid-15-lcd-energizer": "Nemtek Druid 15 LCD Energizer",
  "nemtek-druid-18-lcd-energizer": "Nemtek Druid 18 LCD Energizer",
  "nemtek-druid-18lcd-energizer": "Nemtek Druid 18LCD Energizer",
  "nemtek-druid-2-zone-keypad": "Nemtek Druid 2 Zone Keypad",
  "nemtek-druid-25-lcd-energizer": "Nemtek Druid 25 LCD Energizer",
  "nemtek-druid-28-lcd-electric-fence-energizer": "Nemtek Druid 28 LCD Electric Fence Energizer",
  "nemtek-druid-4-zone-keypad": "Nemtek Druid 4 Zone Keypad",
  "nemtek-druid-single-zone-keypad": "Nemtek Druid Single Zone Keypad",
  "nemtek-lightning-diverter-kit-dealers-in-kenya-nemtek-lightning-diverter-kit": "Nemtek Lightning Inhibitor and Diverter",
  "nemtek-sliding-gate-contacts": "Nemtek Sliding Gate Contacts",
  "nemtek-wizord-2-energizer": "Nemtek Wizord 2 Energizer",
  "nemtek-wizord-4-energizer": "Nemtek Wizord 4 Energizer",
  "notifier-b501-plug-in-detector-base": "Notifier B501 plug-in Detector Base",
  "override-key-switch": "Override Key Switch",
  "panduit-tx6a-category-6a-u-utp-copper-cable": "Panduit TX6A™ Category 6A U/UTP Copper Cable",
  "panic-buttons": "Panic Button",
  "panic-button-remote-ptx1-sherlotronics": "Panic Button Remote PTX1- Sherlotronics",
  "photoelectric-beam-sensor-kenya": "Photoelectric Beam Sensor 100m",
  "pop-rivet-gun": "Pop rivet gun",
  "pop-rivet-gun-2": "Pop Rivet Gun",
  "porcelain-bullnose-strainer-insulator": "Porcelain Bullnose Strainer Insulator",
  "porcelain-electric-fence-insulators-4": "Porcelain electric fence insulators",
  "prosys-control-panel-features-risco-prosys-plus-panel": "Prosys Control Panel",
  "prosys-lcd-keypads": "Prosys LCD Keypads",
  "prysmian-1-5mm%c2%b2-fp200-gold-fire-fire-resistant-alarm-cable": "Prysmian 1.5mm² FP200 Gold Fire Fire Resistant Alarm Cable",
  "push-to-exit-button": "Push to Exit Button",
  "razor-wire-450mm": "Razor Wire 450mm",
  "razor-wire-730mm": "Razor Wire 730mm",
  "reflective-fire-exit-sign": "Reflective Fire Exit Sign",
  "relay-board": "Relay Board",
  "rfid-cards-for-access-control": "RFID Cards for Access Control",
  "rg59-coaxial-cable-with-power-100-meters": "RG59 Coaxial Cable With Power 100 Meters",
  "rg59-coaxial-cable-with-power-200-meters": "RG59 Coaxial Cable With Power 200 Meters",
  "rg59-copper-coaxial-cable-305-meters": "RG59 Copper Coaxial Cable 305 Meters",
  "lightsys-alarm-panel": "Risco Lightsys Alarm Panel",
  "risco-lightsys-gsm-module": "Risco Lightsys GSM Module",
  "risco-lightsys-lcd-keypad": "Risco Lightsys LCD Keypad",
  "rj45-hdmi-extender": "Rj45 HDMI Extender",
  "roller-shutter-magnetic-door-sensor": "Roller Shutter Magnetic Door Sensor",
  "s922-portable-time-attendance-device": "S922 Portable Time Attendance Device",
  "safety-parking-convex-mirror": "Safety parking convex mirror",
  "secolink-graphic-lcd-keypads-km24a-and-km24g": "Secolink Graphic LCD keypads KM24A and KM24G",
  "sestic-glue": "Sestic Glue",
  "sherlo-tronics-ptx1-panic-button": "SHERLO TRONICS PTX1 Panic button",
  "sherlotronic-remote-button": "Sherlotronic Remote Button",
  "sherlotronics-4-channel-receiver-500m-range-rx4-500": "Sherlotronics 4 Channel Receiver 500m Range RX4-500",
  "sherlotronics-power-supply-unit-3-2a-2": "Sherlotronics Power Supply Unit 3.2A",
  "sherlotronics-remote-button-tx1": "Sherlotronics Remote Button TX1",
  "sherlotronics-remote-kit": "Sherlotronics Remote Kit",
  "sherlotronics-receiver-rx4-500-available-in-kenya": "Sherlotronics RX4-500 Long Range 4 Channel Receiver",
  "siemon-cat-6-category-6-unshielded-twisted-pair-utp-cable": "Siemon Cat 6 Category-6 Unshielded Twisted Pair (UTP) Cable",
  "siren-box": "Siren Box",
  "siren-horn-15-watts": "Siren Horn 15 watts",
  "siren-horn-30-watt": "Siren Horn 30 Watt",
  "siren-kit-alarm-kit": "Siren Kit",
  "sliding-gate-guide-rollers": "Sliding Gate Guide Rollers",
  "sliding-gate-rollers-wheels": "Sliding Gate Rollers Wheels",
  "sliding-gate-steel-gear-rack-rail": "Sliding Gate Steel Gear Rack/Rail",
  "sliding-gate-wheels-rollers": "Sliding Gate Wheels/rollers",
  "solar-powered-4g-intelligent-ptz-camera": "Solar powered 4G Intelligent ptz camera",
  "stafix-46000w-mains-energizer": "Stafix 46000W Mains Energizer",
  "stafix-x18i-energizer": "Stafix X18i Energizer",
  "stafix-x3-energizer": "Stafix X3 Energizer",
  "stafix-x6-energizer": "Stafix x6 Energizer",
  "stainless-steel-exit-button": "Stainless Steel Exit Button",
  "standalone-access-control-keypad-s601em": "Standalone Access Control Keypad S601em",
  "strainer-insulators-for-electric-fence": "Strainer Insulators For Electric Fence",
  "suprema-bew2-odp-outdoor-ip-fingerprint-reader": "Suprema BEW2-ODP outdoor IP fingerprint reader",
  "suprema-bio-mini-slim-2-fap20-fingerprint-scanner": "Suprema Bio Mini Slim 2 FAP20 fingerprint Scanner",
  "suprema-bioentry-p2": "Suprema BioEntry P2",
  "suprema-bioentry-plus": "Suprema BioEntry Plus",
  "suprema-biostation-3-facial-recognition-bs3-db": "Suprema BioStation 3 Facial Recognition BS3-DB",
  "suprema-biostation-l2-fingerprint-biometric-device": "Suprema BioStation L2 Fingerprint Biometric Device",
  "suprema-xp2-mdpb-xpass-2-outdoor-compact-rfid-reader": "Suprema XP2-MDPB XPass 2 Outdoor Compact RFID Reader",
  "suprema-xpass-d2": "Suprema XPass D2",
  "surge-protector-for-centurion-gate-motors": "Surge protector for Centurion Gate Motors",
  "t5577-125khz-writable-thin-proximity-cards": "T5577 125KHz Writable Thin Proximity Cards",
  "tk4100-rfid-cards": "tk4100 rfid cards",
  "triband-gsm-signal-booster-2g-3g-4g": "Triband GSM Signal Booster (2G 3G 4G)",
  "u-bracket-for-magnetic-lock": "U Bracket For Magnetic Lock",
  "uv-treated-electric-fence-w-insulators": "Uv Treated Electric Fence W insulators",
  "w-post-electric-fence": "W Post Electric Fence",
  "wd-1tb-surveillance-hard-disk": "WD 1TB surveillance Hard Disk",
  "wd-500gb-internal-hard-disk": "WD 500GB Internal Hard Disk",
  "wd-purple-2tb-surveillance-hard-disk-drive": "WD Purple 2TB Surveillance Hard Disk Drive",
  "wd-purple-pro-surveillance-hard-drive-10tb-512mb-wd101purp": "WD Purple Pro Surveillance Hard Drive 10TB, 512MB – WD101PURP",
  "weather-proof-conventional-fire-strobe-sounder": "Weather Proof Conventional Fire Strobe Sounder",
  "wifi-bulb-camera-1080p-suppliers-in-kenya": "Wifi Bulb Camera",
  "yuasa-12v-17ah-sealed-lead-acid-battery": "Yuasa 12V 17AH Sealed Lead Acid Battery",
  "zkteco-f18-biometric-reader": "Zkteco F18 Biometric Reader",
  "zkteco-f21-biometric-reader-advanced-access-control-kenya": "ZKTeco F21 Biometric Device",
  "zkteco-f22-fingerprint-reader": "ZKteco F22 Fingerprint Reader",
  "zkteco-inbio-4-door-access-controller-3": "Zkteco Inbio 4 Door Access Controller",
  "zkteco-k40-time-attendance-terminal": "ZKTeco K40 Time Attendance Terminal",
  "zkteco-mb360": "ZKTeco MB360",
  "zkteco-mb560-vl": "ZKTeco MB560-VL",
  "zkteco-s922-portable-bio-metric-system": "ZKteco S922 portable bio-metric system",
  "speedface-v5l-suppliers-kenya": "Zkteco SpeedFace V5L",
  "zkteco-speedface-v4l": "ZKTeco SpeedFace-V4L",
  "zkteco-tf1700-biometric-reader": "Zkteco TF1700 Biometric Reader",
  "zkteco-zk4500-fingerprint-scanner-2": "ZKTeco zk4500 Fingerprint scanner",
});
